---
- name: controller
  hosts: controller
  remote_user: ubuntu
  become: true
  become_user: root
  become_method: sudo

  roles:
  - role: roles-local/kube-tls-node
  - role: roles-local/kube-controller
